### ISSUE TITLE
Error on dbt debug

### ISSUE THREAD

**Issue by dpavancini** [techindicium/dbt-oracle#1]
When testing the connection on dbt debug, this error appears. Nevertheless, the connection is sucessful.

Oracle error: ORA-00923: FROM keyword not found where expected
  Connection test: ERROR

dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  ORA-00923: FROM keyword not found where expected

**Comment by fabrice-etanchaud** [comment]
Hi @dpavancini , I just started using your great adapter, have not dived in the code, but it seems like a missing 'FROM DUAL' clause, as other dbs usually only need a 'SELECT something' when issuing computed only fields. I can remember mandatory 'SELECT 1' queries hidden in several parts of dbt, it could be the problem. Thank you again for the adapter !

**Comment by fabrice-etanchaud** [comment]
debug command issues a "select 1 as id", that should be "select 1 as id from dual" in our case.
In order to make this work, this debug sql command should be dispatched in each adapter (maybe only in SQLAdapter and OracleAdapter should do the job). This has to be discussed with the dbt's team.

[select 1 as id](https://github.com/fishtown-analytics/dbt/blob/74c78ef9279638d14949d4e93ae76166d4fd8022/core/dbt/task/debug.py#L338)

**Comment by vitoravancini** [comment]
That looks bad, I was trying to find a way to overwrite this reconnect, but I havent found a solution yet. But I guess this is just for reconnect, the regular dbt debug can be fixed using you your suggestions @fabrice-etanchaud. I will try to take a look tonight. Pr's are also very wellcome!

**Comment by fabrice-etanchaud** [comment]
Hi @vitoravancini, yes, I have a few lines of code to suggest, but I would like to have a better understanding of the dbt's adapter philosophy before I do a PR, I don't want to waste your time.

**Comment by dpavancini** [comment]
Hi @fabrice-etanchaud, was this issue addressed on your latest PR?

**Comment by fabrice-etanchaud** [comment]
Hi @dpavancini, on our side, this would just be a matter of writing one adapter macro. The work is mostly on dbt's side, and I am not enough skilled at the moment to propose a PR on such a great piece of software !

Best

**Comment by vitoravancini** [comment]
dbt debug works now, closing this
