### ISSUE TITLE
Relationship schema test not implemented

### ISSUE THREAD

**Issue by dpavancini** [techindicium/dbt-oracle#4]
Example test:
![image](https://user-images.githubusercontent.com/13836121/79496899-358b5a80-7ffd-11ea-809d-e02bc2afd33f.png)

Result:

![image](https://user-images.githubusercontent.com/13836121/79496877-2e644c80-7ffd-11ea-9b30-309d04a0415d.png)

**Comment by fabrice-etanchaud** [comment]
The AS keyword for table alias should be removed, one has to create a specific relationships.sql file : 

```
select count(*) as validation_errors
from (
    select {{ column_name }} as id from {{ model }}
) <<as>> child
left join (
    select {{ field }} as id from {{ to }}
) <<as>> parent on parent.id = child.id
where child.id is not null
  and parent.id is null
```

[relationships.sql](https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/core/dbt/include/global_project/macros/schema_tests/relationships.sql)

**Comment by fabrice-etanchaud** [comment]
As of dbt 0.18.0, schema tests are using adapter dispatch scheme.
The last pull request already contains an ad-hoc version of the [schema_tests](https://github.com/techindicium/dbt-oracle/blob/develop/dbt/include/oracle/macros/schema_tests.sql).
IMHO one can close this issue !
